name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      COMMIT_EMAIL: 7089284+tudddorrr@users.noreply.github.com
      COMMIT_MESSAGE: "Release https://github.com/TaloDev/unity/releases/tag/${{ github.ref_name }}"

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Copy files
        run: |
          mkdir -p Release/Samples~
          cp -a Packages/com.trytalo.talo/. Release
          cp -a Assets/. Release/Samples~/Playground

      - name: Copy to package repo (main branch)
        uses: tudddorrr/github-action-push-to-another-repository@main
        if: "!contains(github.event.head_commit.message, '--no-release') && !contains(github.event.head_commit.message, 'pre.')"
        env:
          API_TOKEN_GITHUB: ${{ secrets.PAT }}
        with:
          source-directory: Release
          destination-github-username: TaloDev
          destination-repository-name: unity-package
          user-email: ${{ env.COMMIT_EMAIL }}
          commit-message: ${{ env.COMMIT_MESSAGE }}

      - name: Copy to package repo (version branch)
        uses: tudddorrr/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.PAT }}
        with:
          source-directory: Release
          destination-github-username: TaloDev
          destination-repository-name: unity-package
          user-email: ${{ env.COMMIT_EMAIL }}
          commit-message: ${{ env.COMMIT_MESSAGE }}
          target-branch: ${{ github.ref_name }}

      - name: Create artifact
        run: |
          cd Release
          npm pack

      - name: Create release
        uses: softprops/action-gh-release@v1
        if: "!contains(github.event.head_commit.message, '--no-release')"
        with:
          generate_release_notes: true
          prerelease: ${{ contains(github.event.head_commit.message, 'pre.') }}
          files: Release/*.tgz
