name: Release

on:
  workflow_dispatch:

env:
  OUTPUT_DIR: Talo

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Create output directory
        run: mkdir -p "${{ env.OUTPUT_DIR }}"

      - name: Create Unity Package
        uses: natsuneko-laboratory/create-unitypackage@v3
        with:
          files-glob: ./Assets/Talo Game Services/**/*
          dest: ${{ env.OUTPUT_DIR }}/talo.unitypackage

      - name: Zip package
        id: zip-package
        run: |
          filepath=${{ env.OUTPUT_DIR }}/talo-unity-${{ github.ref_name }}.zip
          echo "filepath=$filepath" >> $GITHUB_OUTPUT
          zip $filepath "${{ env.OUTPUT_DIR }}/talo.unitypackage"

      - name: Upload to itch
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: package
          ITCH_GAME: talo-unity
          ITCH_USER: sleepystudios
          PACKAGE: ${{ steps.zip-package.outputs.filepath }}
          VERSION: ${{ github.ref_name }}

      - name: Create release
        uses: softprops/action-gh-release@v2
        if: "!contains(github.event.head_commit.message, '--no-release')"
        with:
          generate_release_notes: true
          prerelease: ${{ contains(github.event.head_commit.message, 'pre.') }}
          files: ${{ env.OUTPUT_DIR }}/talo.unitypackage
