name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Unity
        uses: game-ci/unity-builder@v3
        with:
          unityVersion: 6000.0.28f1

      - name: Create Unity Package
        run: |
          mkdir -p Release
          unity-editor -batchmode -nographics -quit \
            -projectPath "$(pwd)" \
            -exportPackage "Assets/Talo Game Services" "Release/TaloGameServices.unitypackage"

      - name: Upload to itch
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: package
          ITCH_GAME: talo-unity
          ITCH_USER: sleepystudios
          PACKAGE: Release/TaloGameServices.unitypackage
          VERSION: ${{ github.ref_name }}

      - name: Create release
        uses: softprops/action-gh-release@v2
        if: "!contains(github.event.head_commit.message, '--no-release')"
        with:
          generate_release_notes: true
          prerelease: ${{ contains(github.event.head_commit.message, 'pre.') }}
          files: Release/TaloGameServices.unitypackage

      - name: Install Unity CLI
        run: |
          npm install -g unitypackage-cli

      - name: Upload to Unity Asset Store
        env:
          UNITY_PUBLISHER_ID: ${{ secrets.UNITY_PUBLISHER_ID }}
          UNITY_PACKAGE_ID: ${{ secrets.UNITY_PACKAGE_ID }}
          UNITY_ACCESS_TOKEN: ${{ secrets.UNITY_ACCESS_TOKEN }}
        run: |
          unitypackage upload \
            --package "Release/TaloGameServices.unitypackage" \
            --publisher-id "$UNITY_PUBLISHER_ID" \
            --package-id "$UNITY_PACKAGE_ID" \
            --access-token "$UNITY_ACCESS_TOKEN"
