name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Unity
        uses: game-ci/unity-builder@v4
        with:
          unityVersion: 6000.0.28f1

      - name: Create Unity Package
        run: |
          mkdir -p Release
          unity-editor -batchmode -nographics -quit \
            -projectPath "$(pwd)" \
            -exportPackage "Assets/Talo Game Services" "Release/talo.unitypackage"

      - name: Upload to itch
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: package
          ITCH_GAME: talo-unity
          ITCH_USER: sleepystudios
          PACKAGE: Release/talo.unitypackage
          VERSION: ${{ github.ref_name }}

      - name: Create release
        uses: softprops/action-gh-release@v2
        if: "!contains(github.event.head_commit.message, '--no-release')"
        with:
          generate_release_notes: true
          prerelease: ${{ contains(github.event.head_commit.message, 'pre.') }}
          files: Release/talo.unitypackage
