
name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Copy files
        run: |
          mkdir -p Release/Samples~
          cp -a Packages/com.trytalo.talo/. Release
          cp -a Assets/. Release/Samples~/Playground

      - name: Copy to package repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.PAT }}
        with:
          source-directory: Release
          destination-github-username: TaloDev
          destination-repository-name: unity-package
          user-email: 7089284+tudddorrr@users.noreply.github.com
          commit-message: "Release https://github.com/TaloDev/unity/releases/tag/${{ github.ref_name }}"

      - name: Create artifact
        run: |
          cd Release
          npm pack

      - name: Create release
        uses: softprops/action-gh-release@v1
        if: "!contains(github.event.head_commit.message, '--no-release')"
        with:
          generate_release_notes: true
          files: Release/*.tgz
