
name: Release

on:
  push:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create release
        run: |
          mkdir -p Release/Samples~
          cp -a Packages/com.trytalo.talo/. Release
          mv Assets Release/Samples~/Playground
          tar -czvf release.tar.gz Release
          
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: release.tar.gz
