
name: Release

on:
  push:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup release folder
        run: |
          mkdir -p Release/Samples~
          cp -a Packages/com.trytalo.talo/. Release
          mv Assets Release/Samples~/Playground

      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          filename: 'release.tar.gz'
          type: 'tar'
          directory: 'Release'
          
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: Release/release.tar.gz
